apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  namespace: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      volumes:
        - name: items-shared
          configMap:
            name: items-config
            items:
              - key: listofitems.txt
                path: listofitems.txt
      containers:
        - name: web
          image: reservation-app:5         # keep your working tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: items-shared
              mountPath: /items
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 10
